title: hello,world
author: Goo-V
email: 956810543@qq.com
description: > # this means to ignore newlines until "baseurl:"
  it is very cool,but it is a little difficult

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
